version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - 3333:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    env_file: ./wordpress/wp.env
  apache:
    build: ./apache
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
      - ./apache/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - 18080:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
  wordpress:
    image: wordpress:latest
    ports:
      - 28080:80
    depends_on:
      - mysql
    env_file: ./wordpress/wp.env
    volumes:
      - ./wordpress/themes:/var/www/html/wp-content/themes
      - ./wordpress/plugins:/var/www/html/wp-content/plugins